/**
 * The Luna Music logo, as it appears inside the app.
 *
 * Replaces the `G.brandOrb` gradient and its `♪` text glyph, which stood in
 * before there was a real logo. Used in the app bar (`.appbar`) and on the auth
 * screens, so both show the same mark the launcher icon does.
 *
 * Renders assets/images/brand-mark.png rather than the master in assets/brand/:
 * the master is ~2 MB at 1254px, which is not worth shipping for a 27dp orb.
 * Both are generated by `node scripts/render-icons.mjs`.
 */

import { Image } from 'expo-image';
import type { StyleProp, ImageStyle } from 'react-native';

const MARK = require('../assets/images/brand-mark.png');

export function BrandMark({
  size,
  style,
}: {
  size: number;
  style?: StyleProp<ImageStyle>;
}) {
  return (
    <Image
      source={MARK}
      // The artwork already carries its own rounded corners and padding, so it
      // needs no radius or background of its own — `contain` keeps that intact.
      //
      // `flexShrink: 0` is load-bearing: both callers put this in a row next to
      // a text block, and without it the mark gets squeezed to a sliver while
      // the text takes the width.
      style={[{ width: size, height: size, flexShrink: 0 }, style]}
      contentFit="contain"
      accessibilityLabel="Luna Music"
    />
  );
}
